steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/jason-gcp-training/test', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/jason-gcp-training/test' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run', 'deploy', 'test', '--image', 'gcr.io/jason-gcp-training/test', '--region', 'asia-east1', '--allow-unauthenticated' ]
options:
  logging: CLOUD_LOGGING_ONLY
